### ISSUE TITLE
En MisAlertas - Visualizar Ubicacion

### ISSUE THREAD

**Issue by nicoviola91** [nicoviola91/deployTest#1]
No funciona ver ubicacion de la alerta en Mis Alertas. O lo sacamos, o hacemos que funcione.

**Comment by juanagustingallo** [comment]
Listo, le aguregue el link al mapa. AUnque quizas seria mejor borrarlo nose si tiene sentido ese boton

**Comment by juanagustingallo** [comment]
Borrado

**Comment by nicoviola91** [comment]
Cierro el caso
