### ISSUE TITLE
Agregar para borrar un usuario

### ISSUE THREAD

**Issue by gabrielmc85** [nicoviola91/deployTest#11]
no se puede borrar un usuario o no encontré como hacerlo

**Comment by juanagustingallo** [comment]
Habiamos quedado en no borrar nunca nada, lo que se podria hacer es deshabilitarlo quizas?

**Comment by juanagustingallo** [comment]
queda para mas adelante

**Comment by nicoviola91** [comment]
lo cerramos. siaparece la necesidad, se incorporara
