### ISSUE TITLE
error al subir un archivo en una ficha

### ISSUE THREAD

**Issue by gabrielmc85** [nicoviola91/deployTest#12]
probe con un docx, con un jpeg y un txt

![al subuir un archivo en una ficha](https://user-images.githubusercontent.com/29389383/44723381-2eb97800-aaa6-11e8-824b-72d86848d988.jpeg)

**Comment by juanagustingallo** [comment]
Esto creo que es porque debes haber subido un adjunto sin ningun comentario. Ahora agrego para qeu en el mensaje de error te aclare que es porque tenes que escribir algo

**Comment by juanagustingallo** [comment]
Listo

**Comment by nicoviola91** [comment]
Cierro el issue
