### ISSUE TITLE
Alertas -> confirmacion de nueva alerta

### ISSUE THREAD

**Issue by juanagustingallo** [nicoviola91/deployTest#20]
Una vez que termino de cargar, aparece una pagina de dice
 Para hacer un seguimiento de tus alertas hace CLICK ACÁ
 Si querés involucrarte mas en el seguimiento del caso o querés obtener mas información sobre como ayudar. ¡Sumáte! CLICK ACÁ
y cualquiera de los click te lleva a la pagina de carga de una nueva alerta. No debería ir a la pagina de consulta de alertas o pagina de voluntario?

**Comment by nicoviola91** [comment]
listo
