### ISSUE TITLE
Agregar ficha diagnostico integral

### ISSUE THREAD

**Issue by gabrielmc85** [nicoviola91/deployTest#5]
se queda cargando eternamente y nunca aparece

**Comment by juanagustingallo** [comment]
Esto local anda, se les ocurre porque puede estar tirando error?

**Comment by nicoviola91** [comment]
A mi en el online me pasa lo mismo. Después me fijo en el local.

**Comment by nicoviola91** [comment]
en el archivo web.php estaba con minuscula el nombre del controlador en lugar de mayuscula en el get. Entonces no levantaba porque no existia con minuscula
