### ISSUE TITLE
Agregar un empleo

### ISSUE THREAD

**Issue by gabrielmc85** [nicoviola91/deployTest#6]
al grabar un nuevo empleo aparece la pantalla de error, pero el empleo si se guarda
![error guardar trabajo](https://user-images.githubusercontent.com/29389383/44721693-1c890b00-aaa1-11e8-8871-644e0f4e5e60.jpg)

**Comment by nicoviola91** [comment]
Esto @juanagustingallo creo que tiene que ver con la redirección

**Comment by nicoviola91** [comment]
Guarda el empleo pero no la ficha!

**Comment by juanagustingallo** [comment]
Fixed. Habia un error en la foregin key.
