### ISSUE TITLE
Perfiles de usuario

### ISSUE THREAD

**Issue by gabrielmc85** [nicoviola91/deployTest#7]
cuando entras en el perfil de un usuario (el mio por ejemplo) no se registran bien las cosas, probarlo quizas soy yo, pero no me funciono

![image](https://user-images.githubusercontent.com/29389383/44722093-59093680-aaa2-11e8-97b4-47d8e0b21838.png)

**Comment by juanagustingallo** [comment]
Esto no estaba hecho todavia, por eso no andaba. Lo estoy terminando y lo subo

**Comment by juanagustingallo** [comment]
listo, pruebenlo y cualquier cosa me avisan

**Comment by nicoviola91** [comment]
@gabrielmc85 fijate si esto ya funciona porfa. Si funciona cerrá el issue. Gracias
