### ISSUE TITLE
agregar comunidad

### ISSUE THREAD

**Issue by gabrielmc85** [nicoviola91/deployTest#8]
error al agrega, pero despues no la agrega

![image](https://user-images.githubusercontent.com/29389383/44722321-172cc000-aaa3-11e8-8125-f0cc486d2a09.png)

**Comment by juanagustingallo** [comment]
No etnendi bien el problema, es cuando creas una nueva comunidad? cuando agregas comunidad a un usuario? o a un asistido?

**Comment by juanagustingallo** [comment]
Ya lo encontre

**Comment by juanagustingallo** [comment]
Arreglado, tiraba error si no completabas las obseravaciones porque no son nullable en la db

**Comment by nicoviola91** [comment]
posta no eran nullable ??
Cierro el caso
