### ISSUE TITLE
Donaciones

### ISSUE THREAD

**Issue by gabrielmc85** [nicoviola91/deployTest#9]
en el formulario en el apellido aparece de fondo cuit
![donaciones-cuit-enapellido](https://user-images.githubusercontent.com/29389383/44722743-62939e00-aaa4-11e8-9ab5-c709b40dae37.jpg)

**Comment by nicoviola91** [comment]
Corregido. @gabrielmc85 fijate si quedo bien y cerralo porfa.

**Comment by gabrielmc85** [comment]
solucionado
